"""Add column is_subcription to Plan Config

Revision ID: 0bb5694deb7d
Revises: f054a9ebf6bd
Create Date: 2023-07-30 22:06:42.186210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb5694deb7d'
down_revision = 'f054a9ebf6bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_configs', sa.Column('is_subscription', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_configs', 'is_subscription')
    # ### end Alembic commands ###