"""Add file size in document

Revision ID: 1d227a4cef45
Revises: eca2f865b932
Create Date: 2023-08-09 19:12:09.006631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d227a4cef45'
down_revision = 'eca2f865b932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_size')
    # ### end Alembic commands ###