"""Add user with suscription

Revision ID: 5ca8dbcc4466
Revises: 
Create Date: 2023-07-23 23:06:23.383147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca8dbcc4466'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('stripe_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('owner')
    )
    op.create_index(op.f('ix_users_owner'), 'users', ['owner'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('suscription_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.owner'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_users_owner'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###