"""Add supscription with user

Revision ID: 90d0fce6a44f
Revises: 
Create Date: 2023-07-24 12:47:35.395316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d0fce6a44f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('stripe_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('owner'),
    sa.UniqueConstraint('stripe_id')
    )
    op.create_index(op.f('ix_users_owner'), 'users', ['owner'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('subscription_id', sa.String(), nullable=True),
    sa.Column('stripe_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['stripe_id'], ['users.stripe_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_users_owner'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###