"""Add line access token

Revision ID: a36990aecebc
Revises: ef9ae87ed797
Create Date: 2023-09-01 19:26:38.213459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a36990aecebc'
down_revision = 'ef9ae87ed797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('line_channel_access_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'line_channel_access_token')
    # ### end Alembic commands ###