"""Add subscription date

Revision ID: eca2f865b932
Revises: 0bb5694deb7d
Create Date: 2023-07-31 21:10:47.063280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca2f865b932'
down_revision = '0bb5694deb7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('start_at', sa.DateTime(), nullable=True))
    op.add_column('plans', sa.Column('expire_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'expire_at')
    op.drop_column('plans', 'start_at')
    # ### end Alembic commands ###