"""Add fallbck_msg to Collection

Revision ID: ef9ae87ed797
Revises: 1d227a4cef45
Create Date: 2023-08-13 17:10:14.575139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9ae87ed797'
down_revision = '1d227a4cef45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('fallback_msg', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'fallback_msg')
    # ### end Alembic commands ###