"""Add plan config

Revision ID: f054a9ebf6bd
Revises: 90d0fce6a44f
Create Date: 2023-07-26 21:38:49.921252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f054a9ebf6bd'
down_revision = '90d0fce6a44f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_id', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('file_limit', sa.Integer(), nullable=True),
    sa.Column('token_limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_configs_id'), 'plan_configs', ['id'], unique=False)
    op.create_index(op.f('ix_plan_configs_price_id'), 'plan_configs', ['price_id'], unique=False)
    op.add_column('plans', sa.Column('file_remaining', sa.Integer(), nullable=True))
    op.add_column('plans', sa.Column('token_remaining', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'token_remaining')
    op.drop_column('plans', 'file_remaining')
    op.drop_index(op.f('ix_plan_configs_price_id'), table_name='plan_configs')
    op.drop_index(op.f('ix_plan_configs_id'), table_name='plan_configs')
    op.drop_table('plan_configs')
    # ### end Alembic commands ###